---
title: "2024_RLS_Analysis"
author: "Alec"
date: "2024-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(sf) #for spatial data
library(cowplot)
library(rnaturalearth)
library(ggspatial)
library(ggrepel)
library(waver)
library(vcd)
library(sp)
library(viridisLite)
library(dplyr)
```

##Adding in the 2024 data
```{r Loading in the 2024 csv}
RLS_data_2024 <- read_csv(here("./01_raw_data/RLS_CANADA_Bamfield_2024.csv"))
```

```{r Removing first row and unnecessary columns}
factor_cols <- c("site_code", "site_name", "Code")

RLS_data_2024_clean <- RLS_data_2024%>%
  select(c(`Site No.`, `Site Name`, Latitude, Longitude, Date, vis, Time, Depth, Method, Block, Code, Species, Total))%>%
  na.omit()%>%
  rename(site_code = `Site No.`,
         site_name = `Site Name`,
         latitude = Latitude,
         longitude = Longitude,
         survey_date = Date,
         depth = Depth,
         visibility = vis,
         hour = Time,
         total = Total)%>%
   mutate_at(factor_cols, factor)%>%
   mutate(longitude = if_else(site_code == "BMSC2", -125.19876860, longitude))%>%
   group_by(site_code, site_name, latitude, longitude, survey_date, depth, 
           visibility, hour, Code)%>%
  summarise(species_total = sum(total))
```

```{r removing other species and calculating urchin ratio}
 urch_sn_ratio_RLS_2024 <- RLS_data_2024_clean%>%
  pivot_wider(names_from = Code, values_from = species_total)%>%
  mutate(Urchins = mfra,
         Turban_Snails = pgi)%>%
  select(site_code, site_name, latitude, longitude, survey_date, depth, 
           visibility, hour, Urchins, Turban_Snails)%>%
  replace(is.na(.), 0)%>%
  mutate(urch_sn_ratio = log10((Urchins +1) / (Turban_Snails + 1)))%>%
  mutate(survey_date = dmy(survey_date))
```


##Wave exposure calculations

###Making dataframes for the site lat and longs
```{r making 2024 Site data dataframe}
site_data_2024 <- urch_sn_ratio_RLS_2024%>%
  distinct(site_code, site_name, latitude, longitude)
```

```{r Site map }

```

