---
title: "Report Figures"
author: "Alec"
date: "2024-12-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sf)
library(ggspatial)
library(ggrepel)
```

#Loading in the data

##True unshifted data

```{r Loading in the data}
plotting_data <- read_csv(here("./03_clean_data/urch_sn_ratio_mod_data.csv"))
```

##Shifted data for better visualization

```{r}
plotting_data_shifted <- read_csv(here("./03_clean_data/plotting_data_shifted.csv"))
```

##Site maps

###Making the map ranges

```{r Seting the ranges for the maps}
#first need to specify the range of the map
lat_min = min(plotting_data$latitude) - 0.05
lat_max = max(plotting_data$latitude) + 0.05

long_min = min(plotting_data$longitude) - 0.05
long_max = max(plotting_data$longitude) + 0.05
```

###Loading in the shape file

```{r Loading in the new high res shape file}
VI_base_layer_hi_res <- read_sf(dsn = here("./01_raw_data/hakai_zip"),
                                stringsAsFactors = F)

VI_base_layer_hi_res_sf <- st_as_sf(VI_base_layer_hi_res)

#specifying the projection to use for the sf
st_crs(VI_base_layer_hi_res_sf) <- "+proj=longlat +datum=WGS84 +no_defs"
```

```{r Loading in the base layer}
VI_base_layer <- read_sf(dsn = here("./01_raw_data/canada_sf_data", ""), 
                         stringsAsFactors = F)
VI_base_layer_sf <- st_as_sf(VI_base_layer)

#specifying the projection for the sf
st_crs(VI_base_layer_sf) <- "+proj=longlat +datum=WGS84 +no_defs"
```

###Loading in the shapefiles for the protected areas

```{r loading in the RCA polygon}
broken_group_RCA <- st_read(here("./01_raw_data/Broken_group_RCA.kml"))
```

```{r Loading in the Numukamis area}
numukamis_area <- st_read(here("./01_raw_data/Numukamis_closed_area.kml"))
```

```{r Loading in the Baeria rocks}
baeria_rocks_er <- st_read(here("./01_raw_data/baeria_rocks.kml"))
```


###Overall site map

```{r Overall Barkley Sound Map}
(overall_Barkley_sound_map <- ggplot()+
    geom_sf(data = VI_base_layer_hi_res_sf, colour = "darkgrey", fill = "lightgrey")+
      geom_point(plotting_data, 
              mapping = aes(x = longitude, y = latitude),
              shape = 21, size = 2, fill = "red")+
   coord_sf(xlim = c(long_min - 0.1, long_max),
           ylim = c(lat_min - 0.05, lat_max)) +
  labs(x = " \nLongitude", y = "Latitude\n ") +
  theme.figure() +
 scale_x_continuous(breaks = c(-125.5, -125.25, -125.0)) +
  scale_y_continuous(breaks = c(48.75, 48.85, 48.95))+
  annotation_north_arrow(
    location = "tr",
    which_north = "true",
    style = north_arrow_fancy_orienteering
  ) +
  annotation_scale(location = "br")+
      geom_point( 
             mapping = aes(x = -125.134813, y = 48.83), shape = 23,
                           fill = "yellow", size = 3))
```

```{r Making the inset map}
(van_isl_map <- ggplot(VI_base_layer_sf) +
  geom_sf() +
  coord_sf(ylim = c(48.3, 50), xlim = c(-126.5, -122.5)) +
  theme.figure() +
  geom_rect(xmin = long_min, xmax = long_max, ymin = lat_min, ymax = lat_max,
            color = "red", fill = NA, linewidth = 1) +
  labs(x = "Longitude", y = "Latitude") +
    theme(axis.text = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_blank())+
   geom_point(
             mapping = aes(x = -123.365041, y = 48.430887), shape = 23,
             fill = "red", size = 5))
```


```{r basemap with inset, fig.width=7.5, fig.height=5.5}

(map_w_inset <- ggdraw(overall_Barkley_sound_map) +
  draw_plot(van_isl_map, x = 0.125, y = 0.138, width = 0.5, height = 0.3))

```

####Saving the overall site map

```{r Saving the overall site map, fig.width=7.5, fig.height=5.5, include=FALSE}
png(filename = here("./04_plots/report_figures/overall_Barkley_sound_map.png"), width = 8, height = 6, 
    units = "in", pointsize = 15, res = 600)

map_w_inset

dev.off()
```


###Site map with points

```{r Overall site map with the site locations}
(overall_site_map <- ggplot()+
    geom_sf(data = VI_base_layer_hi_res_sf, colour = "darkgrey", fill = "lightgrey")+
     geom_sf(data = broken_group_RCA, fill = "blue", colour ="blue", alpha = 0.1)+
   geom_sf(data = numukamis_area, fill = "#481567FF", colour = "#481567FF", alpha = 0.2)+
   geom_sf(data = baeria_rocks_er, fill = "#CD2626", colour = "#CD2626", alpha = 0.2)+
     geom_point(plotting_data, 
              mapping = aes(x = longitude, y = latitude),
              shape = 21, size = 3, fill = "red")+
       coord_sf(xlim = c(long_min + 0.04, long_max - 0.04),
           ylim = c(lat_min + 0.04, lat_max - 0.04)) +
  labs(x = " \nLongitude", y = "Latitude\n ") +
  theme.figure() +
  scale_x_continuous(breaks = c(-125.35, -125.20, -125.05)) +
 # scale_y_continuous(breaks = c(48.80, 48.85, 48.90, 48.95, 49.00))+
  annotation_north_arrow(
    location = "tr",
    which_north = "true",
    style = north_arrow_fancy_orienteering
  ) +
  annotation_scale(location = "br")+
      geom_point( 
             mapping = aes(x = -125.134813, y = 48.83), shape = 23,
                           fill = "yellow", size = 4))
```


####Saving the site map

```{r Saving the overall site map, fig.width=7.5, fig.height=5.5, include=FALSE}
png(filename = here("./04_plots/report_figures/overall_site_map.png"), width = 8, height = 6, 
    units = "in", pointsize = 15, res = 600)

overall_site_map

dev.off()
```

###Urchin Ratio map

```{r Making the plot with the urch to sn ratio on the map 2024}
(urch_sn_ratio_map_figures <- ggplot()+
    geom_sf(data = VI_base_layer_hi_res_sf, colour = "darkgrey", fill = "lightgrey")+
    coord_sf(xlim = c(long_min + 0.04, long_max - 0.04),
           ylim = c(lat_min + 0.04, lat_max - 0.04)) +
  geom_point(data = plotting_data_shifted,
             mapping = aes(x = longitude, y = latitude, color = urch_sn_ratio),
             size = 3,) +
    geom_point(data = plotting_data_shifted,
             mapping = aes(x = longitude, y = latitude, colour = urch_sn_ratio), 
              shape = 1, size = 3, colour = "black") + 
  scale_colour_gradient2(
    low = "blue",          # Color for negative values
    mid = "white",         # Color for zero
    high = "red",          # Color for positive values
    midpoint = 0           # Set the midpoint to zero
  ) +
  labs(x = " \nLongitude", y = "Latitude\n ", colour = " Log Urchin to\n Snail Ratio") +
  theme.figure() +
  scale_x_continuous(breaks = c(-125.35, -125.20, -125.05)) +
 # scale_y_continuous(breaks = c(48.80, 48.85, 48.90, 48.95, 49.00))+
  annotation_north_arrow(
    location = "tr",
    which_north = "true",
    style = north_arrow_fancy_orienteering
  ) +
  annotation_scale(location = "br")+
     geom_point( 
             mapping = aes(x = -125.134813, y = 48.83), shape = 23,
                           fill = "yellow", size = 4))
```

####Saving the site map

```{r Saving the overall site map, fig.width=7.5, fig.height=5.5, include=FALSE}
png(filename = here("./04_plots/report_figures/urch_sn_ratio_map.png"), width = 7.5, height = 4, 
    units = "in", pointsize = 15, res = 600)

urch_sn_ratio_map_figures

dev.off()
```