---
title: "RLS Modelling"
author: "Alec"
date: "2024-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(mgcv)
library(DHARMa)
library(mgcViz)
library(ggeffects)
library(gratia)
library(geoR)
```


#Modelling the environmental variables

##Loading in the data
```{r Loading in the data}
env_mod_data <- read_csv(here("./03_clean_data/urch_sn_ratio_mod_data.csv"))
```

```{r Scaling the explanatory variables and converting substrate type to factor}
env_mod_data$sst_scale <- scale(env_mod_data$sst)
env_mod_data$avg_fetch_scale <- scale(env_mod_data$avg_fetch)
env_mod_data$dominant_score <- as.factor(env_mod_data$dominant_score)
levels(env_mod_data$dominant_score) <- list(loose = "3", solid = "4")
```

##Plotting EVs against urch sn ratio

```{r ratio against fetch}
ggplot(env_mod_data, aes(x = avg_fetch_scale, y = urch_sn_ratio))+
  geom_point()+
  theme.figure()
```

```{r ratio against sst}
ggplot(env_mod_data, aes(x = sst, y = urch_sn_ratio))+
  geom_point()+
  theme.figure()
```

```{r ratio against substrate type}
ggplot(env_mod_data, aes(x = dominant_score, y = urch_sn_ratio))+
  geom_point()+
  theme.figure()
```

##Building the GAM

###No spatial autocorrelation term
```{r Making a gam with no spatial autocorrelation term to start}
env_mod <- gam(urch_sn_ratio ~ s(sst_scale) + s(avg_fetch_scale) + dominant_score,
               data = env_mod_data,
               family = gaussian(link = "identity"),
               method = 'REML',
               select = TRUE)

set.seed(13)
gam.check(env_mod, rep = 500)

plot(env_mod)
```


```{r Checking the model fit with DHARMa}
env_mod_resids <- simulateResiduals(env_mod)
plot(env_mod_resids)
```

```{r Plotting the model output}
draw(env_mod, residuals = TRUE)
```


###Visualizing the model output
```{r}
sst_sm <- smooth_estimates(env_mod, select = "s(sst_scale)")
avg_fetch_sm <- smooth_estimates(env_mod, select = "s(avg_fetch_scale)")
```

```{r Plotting the temp model estimates}
sst_sm |>
  add_confint() |>
  ggplot(aes(y = .estimate, x = sst_scale))+
    geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci),
         alpha = 0.2, fill = "forestgreen")+
  geom_line(colour = "forestgreen", linewidth = 1.5)+
  labs(y = "Partial Effect", x = "sst_scaled")+
  theme.figure()
```


```{r Plotting the fetch model estimates}
avg_fetch_sm |>
  add_confint() |>
  ggplot(aes(y = .estimate, x = avg_fetch_scale))+
    geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci),
         alpha = 0.2, fill = "forestgreen")+
  geom_line(colour = "forestgreen", linewidth = 1.5)+
  labs(y = "Partial Effect", x = "avg_fetch_scaled")+
  theme.figure()
```

```{r}
env_mod_no_fetch <- gam(urch_sn_ratio ~ s(sst_scale) + dominant_score, data = env_mod_data,
                        method = 'REML',
                        family = gaussian(link = "identity"),
                        select = FALSE)

gam.check(env_mod_no_fetch, rep = 500)


AIC(env_mod, env_mod_no_fetch)%>%
arrange(AIC)%>%
  mutate(delta_AIC = AIC - AIC[1])


itsadug::compareML(env_mod, env_mod_no_fetch)
```

```{r}
draw(env_mod_no_fetch)
```


###With spatial autocorrelation term

```{r Building the gam with the spatial autocorrelation term}
env_mod_sp <- gam(urch_sn_ratio ~ s(sst_scale) + s(avg_fetch_scale) + dominant_score + s(latitude, longitude, k = 10),
                  data = env_mod_data, 
                  method = 'REML',
                  select = TRUE)   #In this case I have added the lat long as an interaction term directly in the model

gam.check(env_mod_sp, rep = 500)
plot(env_mod_sp, residuals = TRUE)
```

```{r}
env_mod_sp_resid <- simulateResiduals(env_mod_sp)
plot(env_mod_sp_resid)
```

```{r}
draw(env_mod_sp)
```



```{r Building the gam with the spatial autocorrelation term}
env_mod_sp_gp <- gam(urch_sn_ratio ~ s(sst_scale) + s(avg_fetch_scale) + dominant_score + s(latitude, longitude, bs = "gp", k = 10),
                  data = env_mod_data, 
                  family = gaussian(link = "identity"),
                  method = 'REML',
                  select = TRUE)   #In this case I have added the lat long as an interaction term directly in the model

set.seed(10)
gam.check(env_mod_sp_gp, rep = 500)
plot(env_mod_sp_gp)
```


```{r Building gamm with spatial autocorrelation term}
env_mod_sp_cor <- gamm(urch_sn_ratio ~ s(sst_scale) + s(avg_fetch_scale) + dominant_score, 
                        data = env_mod_data,
                       family = gaussian(link = "identity"),
                       correlation = corSpher(form = ~ longitude + latitude), 
                       method = 'REML',
                       select = TRUE)

set.seed(100)
gam.check(env_mod_sp_cor, rep = 500)
plot(env_mod_sp_cor)
```


####Testing the data to see if it is spatially correlated

```{r Using Moran's I test on the data}
inv_dist <- with(env_mod_data, 1/dist(cbind(latitude, longitude), diag = TRUE, upper = TRUE))
inv_dist <- as.matrix(inv_dist)
inv_dist[is.infinite(inv_dist)] <- 0.1
ape::Moran.I(env_mod_data$urch_sn_ratio, weight = inv_dist, scaled = TRUE)
```

```{r Plotting a semi-variogram to confirm that the data is not spatially autocorrelated}
lat_long_dist <- dist(urch_sn_ratio_mod_2024[, 2:3])
summary(lat_long_dist)

variog_data <- urch_sn_ratio_mod_2024%>%
  select(c(latitude, longitude, urch_sn_ratio))
variog_data <- as.geodata(variog_data)

plot(variog_data)
points(variog_data)
```


####Testing the data for colinearity


